config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'restaurants#index'
  
  namespace :admin do
    root 'restaurants#index'
    resources :restaurants
    resources :categories
  end
  
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
      
    collection do
      get :newsfeed # 瀏覽所有餐廳的最新動態
      get :ranking # TOP 10
    end
    
    member do
      get :dashboard # 瀏覽個別餐廳的 Dashboard
      post :favorite
      post :unfavorite
    end

  end
  
  resources :categories, only: :show
  
  resources :users, only: [:index, :show, :edit, :update]
  
  resources :followships, only: [:create, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  mount_uploader :avatar, AvatarUploader
  
  # 「使用者評論很多餐廳」的多對多關聯
  has_many :comments, dependent: :restrict_with_error
  has_many :commented_restaurants, through: :comments, source: :restaurant

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant
  
  # 一個 User 擁有很多追蹤紀錄 (followships)
  # 透過追蹤紀錄，一個 User 追蹤很多其他 User (followings)
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships
  
  def admin?
    self.role == "admin"
  end
  
  def following?(user)
    self.followings.include?(user)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update]
  
  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.commented_restaurants.uniq
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 col-md-offset-3">

      <h3>Edit Profile</h3>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :intro, "自我介紹" %>
          <%= f.text_area :intro, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :avatar, "大頭照上傳" %>
          <%= image_tag @user.avatar if @user.avatar? %>
          <%= f.file_field :avatar %>
        </div>
        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-primary" %>
          <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <ul class="nav nav-tabs">
      <li role="presentation" >
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態' %>
      </li>
      
      <li role="presentation" class="active">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>

  </div>
</div>

<div class="container">
  <div class="row">

    <div class="col-md-12">
      <div class="page-header">
        <h1>美食達人</h1>
      </div>
    </div>

    <% @users.each do |user| %>
      <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">

        <%= link_to user_path(user) do %>
          <!-- 可先利用 Placeholder 如 <img src="http://via.placeholder.com/128x128"> 產生圖片 -->
          <%= image_tag(user.avatar, class: "img-rounded") %>
          <h4><%= user.name %></h4>
        <% end %>

        <%= render partial: "aaa/toggle_follow", locals: { x: user } %>

      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <!-- page-header 裡面顯示個人檔案資料 -->
      <div class="page-header">

        <div class="col-md-3 col-sm-4">
          <div class="text-center">
            <%= image_tag @user.avatar, class: "img-responsive img-rounded" %>
          </div>
        </div>

        <div class="col-md-9 col-sm-8">
          <h2><%= @user.name %></h2>
          <p><strong><%= @user.email %></strong></p>
          <div><%= simple_format @user.intro %></div>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="clearfix"></div>

      </div>

      <br>
      
      <div>
        <!-- 顯示已評論餐廳的清單 -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</h3>
          </div>
          <div class="panel-body">
            <% @commented_restaurants.each do |restaurant| %>
              <%= link_to restaurant_path(restaurant) do %>
              <div class="my-restaurant">
                <div>
                  <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
                </div>
                <h5><%= restaurant.name %></h5>
              </div>
              <% end %>

            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>