config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'restaurants#index'
  
  namespace :admin do
    root 'restaurants#index'
    resources :restaurants
    resources :categories
  end
  
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
      
    collection do
      get :newsfeed # 瀏覽所有餐廳的最新動態
      get :ranking # TOP 10
    end
    
    member do
      get :dashboard # 瀏覽個別餐廳的 Dashboard
      post :favorite
      post :unfavorite
    end

  end
  
  resources :categories, only: :show
  
  resources :users, only: [:index, :show, :edit, :update]
  
  resources :followships, only: [:create, :destroy]
  
end

app/views/aaa/_restaurant_list.html.erb
<!-- restaurants list，有多寫 restaurant-item 的 class style -->
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= image_tag restaurant.image, class: "img-responsive center-block" %>
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-default"><%= restaurant.category.name %><p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
        <%= render partial: "aaa/toggle_favorite", locals: { x: restaurant } %>
      </div>
    </div>
  </div>
<% end %>

<!-- 有generate kaminari paginate bootstrap style -->
<div class="text-center">
  <%= paginate @restaurants %>
</div>

app/views/aaa/_tabbar.html.erb
<div class="container">
  <div class="row">

    <!-- 使用 Bootstrap components 的 Nav Tabs -->
    <!-- https://getbootstrap.com/docs/3.3/components/#nav-tabs -->
    <ul class="nav nav-tabs">
      <li role="presentation" class="<%= 'active' if selected_item == '首頁' %>">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation" class="<%= 'active' if selected_item == '最新動態' %>">
        <%= link_to '最新動態', newsfeed_restaurants_path %>
      </li>
      <li role="presentation" class="<%= 'active' if selected_item == 'TOP10人氣餐廳' %>">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
    </ul>

  </div>
</div>

<br>

app/views/aaa/_toggle_favorite.html.erb
<% if not x.is_favorited?(current_user) %>
  <%= link_to 'Favorite', favorite_restaurant_path(x), method: :post, class: "btn btn-primary", data: { :"disable-with" => "Waiting...." } %>
<% else %>  
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(x), method: :post, class: "btn btn-info", data: { :"disable-with" => "Waiting...." } %>
<% end %> 

app/views/aaa/_toggle_follow.html.erb
<% if x != current_user %>
  <% if current_user.following?(x) %>
    <!-- 會用 DELETE 動作導向 http://localhost:3000/followships/{user.id} -->
    <%= link_to 'Unfollow', followship_path(x), method: :delete, class: "btn btn-link" %>
  <% else %>
    <!-- 會用 POST 動作導向 http://localhost:3000/followships?following_id={user.id} -->
    <%= link_to 'Follow', followships_path(following_id: x), method: :post, class: "btn btn-default" %>
  <% end %>
<% end %>