config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'restaurants#index'
  
  namespace :admin do
    root 'restaurants#index'
    resources :restaurants
    resources :categories
  end
  
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
      
    collection do
      get :newsfeed # 瀏覽所有餐廳的最新動態
      get :ranking # TOP 10
    end
    
    member do
      get :dashboard # 瀏覽個別餐廳的 Dashboard
      post :favorite
      post :unfavorite
    end

  end
  
  resources :categories, only: :show
  
  resources :users, only: [:index, :show, :edit, :update]
  
  resources :followships, only: [:create, :destroy]
  
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  mount_uploader :image, PhotoUploader
  belongs_to :category

  has_many :comments
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  def is_favorited?(user)
    self.favorited_users.include?(user)
  end
  
  
  
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  def index
    @restaurants = Restaurant.all
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end
  
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end
  
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end
  
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was deleted"
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end
  
  def newsfeed
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end
  
  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end
  
  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end
  
  def favorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    if favorites.exists?
      flash[:alert] = "已被收藏"
    else
      @restaurant.favorites.create!(user: current_user)
    end
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    redirect_back(fallback_location: root_path)
  end

end

app/views/restaurants/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %>'s Dashboard</h1>
      <hr>
      <ul>
        <li>有 <%= @restaurant.comments.count %> 筆評論</li>
        <li>這家餐廳的平均價位為 $XXX</li>
        <li>有 XX 人收藏這家餐廳</li>
      </ul>

    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<%= render partial: "aaa/tabbar", locals: { selected_item: "首頁" } %>

<div class="container">
  <div class="row">
    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
        <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
    <br>

    <%= render partial: "aaa/restaurant_list" %>
      
  </div>
</div>

app/views/restaurants/newsfeed.html.erb
<%= render partial: "aaa/tabbar", locals: { selected_item: "最新動態" } %>

<div class="container">
  <div class="row">

    <div class="col-md-10 col-md-offset-1">
      <h1>餐廳最新動態</h1>
      <hr>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新餐廳</div>
          <div class="panel-body">
            <% @recent_restaurants.each do |restaurant| %>
              <div>
                <h4>
                  <%= link_to restaurant.name, restaurant_path(restaurant) %>
                  <small><%= restaurant.category.name %></small>
                </h4>
                <p><%= truncate(restaurant.description, length: 80) %></p>
                <hr>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新評論</div>
          <div class="panel-body">
            <% @recent_comments.each do |comment| %>
              <div>
                <h4>
                  <%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %>
                </h4>
                <p><%= truncate(comment.content, length: 80) %><small > - by <%= link_to comment.user.name, user_path(comment.user) %></small></p>
                <hr>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/restaurants/ranking.html.erb
<%= render partial: "aaa/tabbar", locals: { selected_item: "TOP10人氣餐廳" } %>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <div class="page-header">
        <h1>Top 10 人氣餐廳 <small>(收藏數最高)</small></h1>
      </div>


      <!-- 有多寫ranking-item的class style-->
      <% @restaurants.each do |restaurant| %>

        <div class="ranking-item">
          <div class="col-md-3">
            <%= link_to restaurant_path(restaurant) do %>
              <%= image_tag restaurant.image, class: "img-responsive center-block" %>
            <% end %>
          </div>
          <div class="col-md-9">
            <h4>
              <%= restaurant.name %>
              <span class="label label-default">收藏數：<%= restaurant.favorites_count %></span>
            </h4>
            <p><%= truncate(restaurant.description, length: 200) %></p>
            <div>
              <%= link_to 'Show', restaurant_path(restaurant), class: "btn btn-primary" %>
              <%= render partial: 'aaa/toggle_favorite', locals: { x: restaurant } %>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>

    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
      <hr>
      <%= link_to 'Dashboard', dashboard_restaurant_path(@restaurant), class: "btn btn-primary" %>
      <%= render partial: "aaa/toggle_favorite", locals: { x: @restaurant } %>
    </div>

    <div class="clearfix"></div>
    <hr>

  </div>
</div>

<div class="container">
  <div class="row">
  
    <!-- 顯示與餐廳相關的評論 -->
    <% @restaurant.comments.each do |comment| %>
    <div>
      <h4><%= comment.user.email.split('@').first %></h4>
      <p><%= simple_format comment.content %></p>
      <p class="text-muted">
        <em><%= time_ago_in_words(comment.created_at) %> ago -</em>
        <% if current_user.admin? %>
          <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
        <% end %>
      </p>
    </div>
    <hr>
    <% end %>

    <!-- 新增評論的表單輸入框 -->
    <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
    <% end %>
  </div>
</div>